App/views/owncenter.py
from flask import Blueprint,render_template,request,flash,redirect,url_for
from flask_login import login_required,current_user
from App.models import Posts as MPosts #模型名
from App.forms import Posts  #表单类名
from datetime import datetime
from App.extensions import cache

center = Blueprint('center',__name__)


#博客管理
@center.route('/blog_manage/')
@login_required
def blog_manage():
    data = current_user.posts.filter_by(pid=0).order_by(MPosts.timestamp.desc())
    return render_template('owncenter/blogmanage.html',data=data)


#博客编辑
@center.route('/edit_blog/<int:pid>/',methods=['GET','POST'])
def edit_blog(pid):
    form = Posts()
    posts = MPosts.query.get(pid) #查询出 博客id对应的博客数据
    if form.validate_on_submit():
        posts.title = request.form.get('title')
        posts.content = request.form.get('content')
        posts.timestamp = datetime.utcnow()
        posts.save()
        flash('博客更新成功')
        cache.clear()
        return redirect(url_for('center.blog_manage'))
    #  给表单添加默认值
    form.title.data = posts.title
    form.content.data = posts.content
    return render_template('owncenter/edit_blog.html',posts=posts,pid=pid,form=form)

#设置为自己查看
@center.route('/see_myself/<int:pid>/')
def see_myself(pid):
    posts = MPosts.query.get(pid) #查询出 博客id对应的博客数据
    posts.state = not posts.state
    posts.save()
    flash('设置成功！')
    cache.clear()
    return redirect(url_for('center.blog_manage'))

#删除
@center.route('/del_posts/<int:pid>/')
def del_posts(pid):
    posts = MPosts.query.get(pid) #查询出 博客id对应的博客数据
    posts.delete()
    flash('删除成功！')
    cache.clear()
    return redirect(url_for('center.blog_manage'))


#我的收藏
@center.route('/collections/')
@login_required
def collections():
    try:
        pid = int(request.args.get('pid'))
        if pid and current_user.is_favorite(pid):
            current_user.remove_favorite(pid)
            flash('取消收藏成功！')
            return redirect(url_for('center.collections'))
    except:
        pass
    data = current_user.favorites.all() #查询所有的收藏
    return render_template('owncenter/collections.html',data=data)

App/templates/owncenter/blogmanage.html
{% extends 'common/base.html' %}
{% block title %}
    博客管理
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        td{
            text-align: center;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}" />
{% endblock %}
{% block pagecontent %}
<form class="form-inline definewidth m20" action="index.html" method="get">
    用户名称：
    <input type="text" name="username" id="username"class="abc input-default" value="" placeholder="输入搜索的博客标题名...">&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp;
{#    <button type="button" class="btn btn-success" id="addnew">新增用户</button>#}
</form>
<table class="table table-bordered table-hover definewidth m10">
    <thead>
    <tr>
        <th>博客id</th>
        <th>博客标题</th>
        <th>访问量</th>
        <th>发表时间</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for row in data %}
	     <tr>
            <td>{{ row.id }}</td>
            <td>{{ row.title }}</td>
            <td>{{ row.visit }}</td>
            <td>{{ moment(row.timestamp).format('Y-M-D H:m:ss') }}</td>
            <td>
                <a href="{{ url_for('center.edit_blog',pid=row.id) }}" target="_blank">编辑</a> |
                <a href="{{ url_for('center.see_myself',pid=row.id) }}">{% if row.state %}所有人可见{% else %}仅自己查看{% endif %}</a> |
                <a href="{{ url_for('center.del_posts',pid=row.id) }}">删除</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

App/templates/owncenter/collections.html
{% extends 'common/base.html' %}
{% block title %}
    博客管理
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        td{
            text-align: center;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}" />
{% endblock %}
{% block pagecontent %}
<form class="form-inline definewidth m20" action="index.html" method="get">
    用户名称：
    <input type="text" name="username" id="username"class="abc input-default" value="" placeholder="输入搜索的博客标题名...">&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp;
{#    <button type="button" class="btn btn-success" id="addnew">新增用户</button>#}
</form>
<table class="table table-bordered table-hover definewidth m10">
    <thead>
    <tr>
        <th>博客id</th>
        <th>博客标题</th>
        <th>访问量</th>
        <th>发表时间</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for row in data %}
	     <tr>
            <td>{{ row.id }}</td>
            <td>{{ row.title }}</td>
            <td>{{ row.visit }}</td>
            <td>{{ moment(row.timestamp).format('Y-M-D H:m:ss') }}</td>
            <td>
                <a href="{{ url_for('center.collections',pid=row.id) }}">取消收藏</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}
{# 点击删除的时候 用jq删除节点 页面不动 #}

App/templates/owncenter/edit_blog.html
{% extends 'common/base.html' %}
{% block title %}
    博客编辑
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
{% endblock %}
{% block pagecontent %}
    <div class="page-header"><h2>博客编辑</h2></div>
    <form action="{{ url_for('center.edit_blog',pid=pid,_external=True) }}" method="post">
        {{ form.csrf_token }}
        {{ form.title.label() }}
        {{ form.title(class='form-control') }}
        {% for err in form.title.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        {{ form.content.label() }}
        {{ form.content(class="ckeditor") }}
        {% for err in form.content.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">修改</button>
    </form>

{% endblock %}