App/views/main.py
from flask import Blueprint,render_template,request,current_app,redirect,url_for
from App.models import Posts
from sqlalchemy import or_,and_
from App.extensions import cache

main = Blueprint('main',__name__)
"""
@main.route('/index/')
@main.route('/')
@cache.memoize(timeout=30) #根据传参进行缓存 设置缓存日期为30秒
def index():
    # 获取页码
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    return redirect(url_for('main.show',page=page))


@main.route('/show/<int:page>/')
@cache.memoize(timeout=60)
def show(page):
    print('你能看到我几次？------------------------------------')
    pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page,
                                                                                        current_app.config['PAGE_NUM'],
                                                                                        False)
    data = pagination.items  # 获取当前页面的数据
    return render_template('main/index.html', data=data, pagination=pagination)
"""






@main.route('/index/')
@main.route('/')
def index():
    # 获取页码
    try:
        page = int(request.args.get('page',1))
    except:
        page = 1

    key = 'page'+str(page) #page1 page2...
    value = cache.get(key) #获取缓存
    if not value:
        print('没走缓存。。。。。。。。。。。。。。')
        pagination = Posts.query.filter_by(pid=0,state=True).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
        data = pagination.items #获取当前页面的数据
        value = render_template('main/index.html',data=data,pagination=pagination)
        cache.set(key,value,timeout=60) #设置缓存失效时间为1分钟

    return value #响应缓存内容


#清除缓存
@main.route('/clear_cache/')
def clear_cache():
    cache.clear()
    return redirect(url_for('main.index'))





"""
@main.route('/index/')
@main.route('/')
# @cache.cached(timeout=30) #设置缓存日期为30秒
@cache.memoize(timeout=30) #根据传参进行缓存 设置缓存日期为30秒
def index():
    print('你能看到我几次？------------------------------------')
    # 获取页码
    try:
        page = int(request.args.get('page',1))
    except:
        page = 1
    pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
    data = pagination.items #获取当前页面的数据
    return render_template('main/index.html',data=data,pagination=pagination)
"""

#博客搜索
@main.route('/search/',methods=['POST','GET'])
def search():
    # 获取页码
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1

    #获取搜索的内容
    if request.method == 'POST':
        word = request.form.get('search','')
    else:
        word = request.args.get('search','')

    pagination = Posts.query.filter(or_(Posts.title.contains(word),Posts.content.contains(word)),and_(Posts.pid==0,Posts.state==True)).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
    data = pagination.items  # 获取当前页面的数据
    return render_template('main/search_detail.html',data=data,pagination=pagination,word=word)

App/views/user.py
from flask import Blueprint,render_template,flash,redirect,url_for
from App.forms import Register,AgainActivate,Login #导入注册表单类
from App.models import User #导入User模型类
from App.email import send_mail
from flask_login import login_required,logout_user,login_user,current_user
from datetime import datetime
from App.extensions import cache


user = Blueprint('user',__name__)
"""
1. 接收到数据(用户名和邮箱唯一性)
2. 保存到数据库（密码加密后的）
3. 生成token值
4. 配置发送邮件
5. 发送激活邮件
6. 提示用户注册成功 前去激活
7. 跳转到登录页面
8.创建激活视图函数...
9.登录...
"""

#注册
@user.route('/register/',methods=['GET','POST'])
def register():
    form = Register()
    if form.validate_on_submit():
        u = User(username=form.username.data,password=form.userpass.data,email=form.email.data)
        u.save()
        token = u.generate_token() #生成token值
        send_mail('账户激活',u.email,'activate',username=u.username,endpoint='user.activate',token=token)
        flash('恭喜注册成功 请前去邮箱进行激活')
        return redirect(url_for('user.login'))
    return render_template('user/register.html',form=form)



#账户激活
@user.route('/activate/<token>/')
def activate(token):
    if User.check_token(token):
        flash('恭喜你激活成功  请登录')
        return redirect(url_for('user.login'))
    else:
        flash('激活失败 请重新再次激活')
        return redirect(url_for('user.register'))


#再次激活
@user.route('/again_activate/',methods=['GET','POST'])
def again_activate():
    form = AgainActivate()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u.check_password(form.userpass.data):
            flash('请输入正确的密码')
        elif u.confirm:
            flash('该账户已经激活 请前往登录')
        else:
            token = u.generate_token()  # 生成token值
            send_mail('账户激活', u.email, 'again_activate', username=u.username, endpoint='user.activate', token=token)
            flash('激活邮件发送成功 请前去邮箱进行激活')
            return redirect(url_for('user.login'))

    return render_template('user/again_activate.html',form=form)


#登录
@user.route('/login/',methods=['GET','POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u.check_password(form.userpass.data):
            flash('请输入正确的密码')
        elif not u.confirm:
            flash('该账户还没有激活 请激活后再次登录')
        else:
            u.lastLogin = datetime.utcnow()
            u.save()
            flash('登录成功！！！')
            login_user(u,remember=form.remember.data)
            return redirect(url_for('main.index'))
    return render_template('user/login.html',form=form)


#退出登录
@user.route('/logout/')
def logout():
    flash('退出成功')
    logout_user()
    cache.clear()
    return redirect(url_for('main.index'))

#必须登录才能访问
@user.route('/test/')
@login_required
def test():
    return 'test'

App/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% block title %}
    test_bootstrap测试
{% endblock %}
{% block metas %}
    {{ super() }}
    <link rel="icon" href="{{ url_for('static',filename='img/1.jpeg',_external=True) }}">
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius:0;">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="
glyphicon glyphicon-fire" aria-hidden="true"></span></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index',_external=True) }}">首页 <span class="sr-only">(current)</span></a></li>
                    <li><a href="{{ url_for('posts.send_posts') }}">发表博客</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" method="post" action="{{ url_for('main.search') }}">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search..." name="search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    {% if current_user.is_authenticated %}
                        <li><a>欢迎：{{ current_user.username }}</a></li>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">个人信息查看和修改</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">修改邮箱</a></li>
                            <li><a href="#">修改头像</a></li>
                            <li><a href="{{ url_for('center.collections') }}">我的收藏</a></li>
                            <li><a href="{{ url_for('center.blog_manage') }}">博客管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('user.logout') }}">退出登录</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{ url_for('user.login') }}">登录</a></li>
                    <li><a href="{{ url_for('user.register') }}">注册</a></li>
                    {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
        {% endfor %}
        {% block pagecontent %}
            pagecontent的内容部分
        {% endblock %}
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    {#  导入时间展示的js代码  #}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

App/templates/common/page.html
{# 加载分页样式 #}
{% macro page(endpoint,pagination) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
                <a {% if pagination.has_prev %}href="{{ url_for(endpoint,page=pagination.prev_num,**kwargs) }}"{% endif %}
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for p in pagination.iter_pages() %}
                <li {% if pagination.page==p %}class="active"{% endif %}><a
                        href="{{ url_for(endpoint,page=p,**kwargs) }}">{{ p }}</a></li>
            {% endfor %}

            <li {% if not pagination.has_next %}class="disabled"{% endif %}>
                <a {% if pagination.has_next %}href="{{ url_for(endpoint,page=pagination.next_num,**kwargs) }}"{% endif %}
                   aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}