App/models/posts.py
from datetime import datetime
from App.extensions import db
from .commonbaseclass import Base #增删改的基类

class Posts(Base,db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(20)) #标题
    content = db.Column(db.Text) #博客内容
    pid = db.Column(db.Integer,default=0) #pid为0则为博客 否则为评论和回复
    path = db.Column(db.Text,default='0,') #路径path
    visit = db.Column(db.Integer,default=0) #访问量
    timestamp = db.Column(db.DateTime,default=datetime.utcnow) #发表的时间
    state = db.Column(db.Boolean,default=True) #默认所有人可见
    uid = db.Column(db.Integer,db.ForeignKey('user.id'))
    def __str__(self):
        return self.title

App/forms/posts.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,StringField
from wtforms.validators import DataRequired,Length

#博客表单
class Posts(FlaskForm):
    title = StringField('标题',validators=[DataRequired('标题不能为空'),Length(min=3,max=20,message='标题内容长度在3～20字之间')],render_kw={'placeholder':'输入标题...','minlength':3,'maxlength':20})
    content = TextAreaField('博客内容',validators=[DataRequired('内容不能为空'),Length(min=20,max=4000,message='博客内容在20～4000字之间')],render_kw={'placeholder':'请输入博客内容','minlength':20,'maxlength':4000})
    submit = SubmitField('发表')

App/views/posts.py
from flask import Blueprint,render_template,flash,redirect,url_for,request,jsonify
from App.forms import Posts
from App.models import Posts as MPosts
from flask_login import current_user

posts = Blueprint('posts',__name__)

#发表博客
@posts.route('/send_posts/',methods=['GET','POST'])
def send_posts():
    form = Posts()
    if not current_user.is_authenticated:
        flash('您还没有登录 请先登录在发表')
    elif form.validate_on_submit():
        p = MPosts(title=form.title.data,content=form.content.data,user=current_user)
        p.save()
        flash('发表成功！去首页进行查看')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/send_posts.html',form=form)



#博客详情
@posts.route('/posts_detail/<int:pid>/')
def posts_detail(pid):
    form = Posts() #作为评论和回复的表单类样式
    data = MPosts.query.get(pid)
    comment = MPosts.query.filter(MPosts.path.contains(str(pid))).order_by(MPosts.path.concat(MPosts.id))
    #select * from posts where path like '%pid%' order by concat(path,id)
    return render_template('posts/posts_detail.html',data=data,comment=comment,form=form)


#添加评论和回复视图函数
@posts.route('/comment/',methods=['POST'])
def comment():
    pid = int(request.form.get('pid')) #博客的自增id
    rid = int(request.form.get('rid')) #回复评论人的id
    if current_user.is_authenticated:
        if rid:
            ppid = rid
        else:
            ppid = pid
        p = MPosts.query.get(ppid)
        MPosts(content=request.form.get('content'),pid=ppid,path=p.path+str(p.id)+',',user=current_user).save()
    else:
        flash('请先登录在发表评论')
    return redirect(url_for('posts.posts_detail',pid=pid))

#收藏操作
@posts.route('/dofavorite/')
def doFavorite():
    try:
        pid = int(request.args.get('pid'))
        if current_user.is_favorite(pid):
            current_user.remove_favorite(pid)
        else:
            current_user.add_favorite(pid)
        return jsonify({'code': 200})
    except:
        return jsonify({'code':500})

App/templates/posts/posts_detail.html
{% extends 'common/base.html' %}
{% block title %}
    博客详情
{% endblock %}
{% block pagecontent %}
    <div class="page-header"><h2>{{ data.title }}</h2></div>
    {{ data.content|safe }}
    <br>
    <span style="float: right;">
        <p style="cursor: pointer;" id="favorite" onclick="dofavorite({{ data.id }})">{% if current_user.is_authenticated %}{% if current_user.is_favorite(data.id) %}取消收藏{% else %}收藏{% endif %}{% else %}收藏{% endif %}</p>
        <p>作者：<span style="font-size: 20px;font-weight: bold;">{{ data.user.username }}</span></p>
        <p>发表于：<span
                style="font-size: 20px;font-weight: bold;">{{ moment(data.timestamp).format('Y-M-D H:m:ss') }}</span></p>
    </span>

    <div class="page-header"><h2>评论内容</h2></div>

    {% for p in comment %}
        <div class="media">
            <div class="media-left media-middle">
                <img class="media-object" src="{{ url_for('static',filename='upload/'+p.user.icon) }}" alt="..."
                     width="50" height="50" style="border-radius: 50px;">
            </div>
            <div class="media-body">
                <h4 class="media-heading">
                    {% if p.pid == data.id %}{{ p.user.username }}{% else %} {{ p.user.username }}回复了{{ p.pid|replay_username }} {% endif %}<span
                        style="color: #ccc;font-size:14px;float: right;">{{ moment(p.timestamp).fromNow() }} <button class="btn btn-success btn-xs" onclick="replay({{ p.id }})">回复</button></span>
                </h4>
                {{ p.content|striptags }}
            </div>
        </div>
        <form action="{{ url_for('posts.comment') }}" method="post" class="replay" id="replay{{ p.id }}">
            {{ form.csrf_token }}
            <input type="hidden" name="pid" value="{{ data.id }}">
            <input type="hidden" name="rid" value="{{ p.id }}">
            {{ form.content(class='form-control',style="resize:none;height:100px;",placeholder="请输入评论内容",required=True,minlength=5,maxlength=100) }}
            <p>评论内容在5~100字之间</p>
            <button type="submit" class="btn btn-success">发表回复</button>
        </form>
    {% endfor %}


    <div class="page-header"><h2>发表评论</h2></div>
    <form action="{{ url_for('posts.comment') }}" method="post">
        {{ form.csrf_token }}
        <input type="hidden" name="pid" value="{{ data.id }}">
        {{ form.content(class='form-control',style="resize:none;height:100px;",placeholder="请输入评论内容",required=True,minlength=5,maxlength=100) }}
        <p>评论内容在5~100字之间</p>
        <button type="submit" class="btn btn-success">发表评论</button>
    </form>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            $('.replay').hide()
        });
        {#    显示回复的文本框    #}
        function replay(id){
            $('.replay').hide();
            $('#replay'+id).show();
        }
        {#    收藏的操作    #}
        function dofavorite(pid) {
            var node = $('#favorite');
{#            alert(node.html());#}
            $.get('{{ url_for("posts.doFavorite",_external=True) }}',{'pid':pid},function (data,status) {
                if(data.code==200){
                    if(node.html()=='收藏'){
                        node.html('取消收藏')
                    }else{
                        node.html('收藏')
                    }
                }else{
                    if(window.confirm('是否前去登录？')){
                        window.location.href='{{ url_for('user.login') }}'
                    }
                }
            })
        }
    </script>
{% endblock %}

App/templates/posts/send_posts.html
{% extends 'common/base.html' %}
{% block title %}
    发表博客
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
{% endblock %}
{% block pagecontent %}
    <form action="{{ url_for('posts.send_posts',_external=True) }}" method="post">
        {{ form.csrf_token }}
        <div class="page-header"><h2>发表博客</h2></div>
        {{ form.title.label() }}
        {{ form.title(class='form-control') }}
        {% for err in form.title.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        {{ form.content.label() }}
        {{ form.content(class="ckeditor") }}
        {% for err in form.content.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">发表</button>
    </form>

{% endblock %}